<!-- formulario de alta de producto -->
<form action="nueva" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input  name="nombre" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Apellido</label>
                <input  name="apellido" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Producto</label>
                <input  name="nombre_producto" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Categoría</label>
                <input  name="tipoDeCompra" type="text" class="form-control">
            </div>
        </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
