<?php require 'templates/form_alta_productos.phtml' ?>

<ul class="list-group">
<?php foreach($products as $product): ?>
    <li class="list-group-item item-product">
    <div class="label">
            <?= htmlspecialchars($product->nombre) ?> <?= htmlspecialchars($product->apellido)?> | <?= htmlspecialchars($product->nombre_producto)?>| <?= htmlspecialchars($product->tipoDeCompra) ?>
        </div>

        <div class="actions">
            <a href="eliminar/<?= $product->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> productos</small></p>


