<?php require 'templates/layout/header.phtml' ?>

<?php require 'templates/form_alta_categorias.phtml' ?>

<ul class="list-group">
<?php foreach($categories as $category): ?>
    <li class="list-group-item item-category">
    <div class="label">
            <?= htmlspecialchars($category->categoria) ?>
        </div>

        <div class="actions">
            <a href="eliminarC/<?= $category->id_venta ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> categorias</small></p>